Santirbe98/PF-ExoOtaku

api/src/routes/index.js
api/src/routes/products.js

Agregue algunas rutas de products

feat(src/routes): Agregado ruta de products

---

api/index.js
api/package.json
api/src/db.js
api/src/models/Color.js
api/src/models/Product.js
api/src/routes/products.js

Arreglado las relaciones de modelos, Ruta POST, GET y GET/:id solucionadas. en las relaciones se corrige "colors" a "color"

fix(src/models & routes): "Arreglado relaciones y rutas"

---

api/package.json
api/src/routes/color.js
api/src/routes/index.js

RUTAS  color.js
GET
GET POR COLOR (PARAMS) 
POST

routes/colorjs && routes/indesjs

---

api/src/routes/Controllers/productsController.js
api/src/routes/products.js

refactor controller de productos y route de product

feat(api/controller/):refactor controller route

---

api/src/routes/Controllers/sizesController.js
api/src/routes/size.js

Fix(src/routes/sizes):implementado delet logico

---

client/package.json
client/src/.text

estructura de carpetas para arrancar a realizar front

feat(client/):Crear archivos y componentes (armar esqueleto)

---

client/src/App.js
client/src/Redux/Actions/index.js
client/src/Redux/Reducer/index.js
client/src/Store/index.js
client/src/index.js

archivo de actions, reducer, store y index de las rutas, listos para ir descomentando y agregando cada actions o route que se vayan haciendo para el front.

fix(client/src)conexcion react-redux

---

api/src/routes/Controllers/productsController.js
api/src/routes/products.js

refactor de las asociaciones en color y size, y el formato de la data q trae las rutas de products

fix(client/controller):refactor controller

---

client/src/App.js
client/src/Components/Cards/Cards.jsx
client/src/Store/index.js

Falta crear componente CARD, y modificar importación: 
import { Card } from './prueba.jsx'
por
import { Card } from './Card/Card.jsx'
@juanetem3n 
// Image: Array[strings]

feat(components/Cards)CrearComponenteCards

---

client/src/Store/index.js
client/src/index.js

Ahora si funciona el cliente, pruebenlo en su repo

fix(client/index.js & store)

---

client/src/App.js
client/src/Components/Cards/Cards.jsx
client/src/Components/Footer/Footer.jsx
client/src/Components/Form/Form.jsx
client/src/Components/Home/Home.jsx
client/src/Components/NavBar/NavBar.jsx
client/src/Components/SearchBar/SearchBar.jsx

Creado los archivos 
- Home
- SearchBar
- NavBar
- Form
- Footer
Creado ruta Form en app.js

feat(client/components): Archivos y carpetas base

---

client/src/App.js
client/src/Components/Error/Error.jsx

Creado el componente 404 con return a home

feat(client/src/components/error): 404

---

api/src/routes/Controllers/filterAllController.js
api/src/routes/Controllers/productsController.js
api/src/routes/Controllers/sizesController.js
api/src/routes/filterAll.js
api/src/routes/index.js
api/src/routes/size.js

refactor filtros. nueva ruta para el filtrado de size

fix(api/filter..):crea carpeta de filtersize

---

client/src/Components/Card/Card.jsx
client/src/Components/Cards/Cards.jsx

Se modifica el parametro Images 
Se descomenta render de Card en Cards.

Feat(component/card//fix/componentCards)

---

client/src/Components/Error/Error.jsx
client/src/Redux/Actions/actionsTypes.js
client/src/Redux/Actions/index.js
client/src/Redux/Reducer/index.js

Agregado el filtrado por catogoria (no renderizado en home)
- Action type creada
- Action function
- Conexion con el reducer
- Agregado copia de estado para no manipular directamente
Corregido el error de idioma en 404

feat(client/src/redux): filter by category

---

client/src/App.js
client/src/Components/About/About.jsx
client/src/Components/Footer/Footer.jsx
client/src/Components/Footer/Footer.module.css
client/src/Components/Help/Help.jsx

Creacion Componentes:
- Help
- About
Componente Footer con 3 Links y h5

ft-footer-component/help && About - salvaarmanasco

---

api/src/routes/Controllers/typesController.js
api/src/routes/types.js

Agregado la ruta deleted en types y tambien su controller

feat(api/src/routes): delete types

---

client/src/Components/Cards/Cards.jsx

fix(client/src/componentss)

---

client/src/Redux/Actions/actionsTypes.js
client/src/Redux/Actions/index.js
client/src/Redux/Reducer/index.js

feat(client/filterAll)creacion de filtros

---

client/src/Components/Home/Home.jsx
client/src/Components/NavBar/NavBar.css
client/src/Components/NavBar/NavBar.jsx

Se incluyo la serchBar adentro de la nav bar, descomentar en  componente Home plz.-

Feat(Client/src/NavBar):LogicaNavBar

---

api/src/routes/Controllers/productsController.js
client/src/Components/Cards/Cards.jsx
client/src/Components/Filter/Filter.jsx
client/src/Components/NavBar/NavBar.jsx
client/src/Redux/Actions/index.js
client/src/Redux/Reducer/index.js

filtros combinados. arreglar linea de colors. para recorrer un map y no sea filter

feat(client/filter)filter combinados

---

client/src/Components/Cards/Cards.jsx
client/src/Components/Paged/Paged.jsx

Se agrego componete de paginado
Se realizo refactoring del componente Cards para incluir paginado

Paged component

---

client/src/Components/Home/Home.jsx
client/src/Redux/Reducer/index.js

Arreglado el filter por colors y type

fix(client/redux/reducer): filtros arreglados

---

api/index.js
api/src/routes/Controllers/productsController.js
api/src/routes/filterAll.js
api/src/routes/products.js
client/package.json
client/src/Components/Cards/Cards.jsx
client/src/Components/Error/Error.jsx
client/src/Components/Filter/Filter.jsx
client/src/Redux/Reducer/index.js

Fix detail+Install Materia UI+remove CGL

Fix detail+Install Materia UI+remove CGL

---

client/src/Components/About/About.jsx
client/src/Components/About/About.module.css
client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/CardDetail/CardDetail.module.css
client/src/Components/Filter/Filter.jsx
client/src/Components/Filter/Filter.module.css
client/src/Components/Home/Home.jsx
client/src/Components/NavBar/NavBar.css
client/src/Components/NavBar/NavBar.jsx
client/src/Components/NavBar/NavBar.module.css

css
buttons
select
acomode el navbar

ft-css/buttons/selects-&&navbar-salvaarmanasco

---

client/src/Components/About/About.jsx
client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/Help/Help.jsx
client/src/Components/Home/Home.jsx
client/src/Components/NavBar/NavBar.jsx

css
colocando nav bar y footer

css-colocando/navbar y footer - salvaarmanasco

---

client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/CardDetail/CardDetail.module.css

Agregado Estilos a CardDetail, solucionado los select de color y size, ahora cada producto tiene los sizes y color de cada uno

feat&fix(client/src/components/CardDetail)

---

client/src/Components/Cards/Cards.jsx
client/src/Components/Paged/Paged.module.css
client/src/Components/PagedSearch/PagedSearch.jsx
client/src/Components/PagedSearch/PagedSearch.module.css

fix-paged-incompleto-salvaarmanasco

---

client/src/Components/Cards/Cards.jsx
client/src/Components/Paged/Paged.module.css
client/src/Components/PagedSearch/PagedSearch.jsx

fix paginado
css botones paginado

fix-paged&&cssbuttonspaged-salvaarmanasco

---

client/src/Components/Cards/Cards.jsx
client/src/Components/Filter/Filter.jsx

arreglo problema de paged junto con filtros

fiex-problema-paged/salvaarmanasco

---

client/src/Components/CardDetail/CardDetail.jsx

Arreglado el Cards details ahora tiene un texto cuando carga la remera

fix(cardDetails): Loading state

---

client/src/Components/Filter/Filter.jsx
client/src/Components/Filter/Filter.module.css
client/src/Components/Form/Form.jsx
client/src/Components/Help/Help.jsx
client/src/Components/Paged/Paged.jsx
client/src/Components/PagedSearch/PagedSearch.jsx

fixes en general
borrado de console.logs
componente help

fix-general&&helpcomponent-salvaarmanasco

---

client/src/Components/Form/Form.jsx

error de form
importaba un archivo que no existia

fix-error de form

---

client/src/Components/Cards/Cards.module.css

fix-vista de cards - salvaarmanasco

---

client/src/Components/Card/Card.jsx

categoryEnCards-salvaarmanasco

---

client/src/Components/Home/Home.jsx
client/src/Components/NavBar/NavBar.jsx

fix-cards&&form

---

client/src/Components/Form/Form.jsx

fix(src/components/form): fix warning

---

client/src/Components/LandingPage/LandingPage.module.css
client/src/Components/PagedSearch/PagedSearch.module.css

fix-retoques-css-salvaarmanasco

---

api/src/db.js
api/src/models/Address.js
api/src/models/Customer.js

Modelos de entidades y relacion para la autenticacion de usuarios / clientes

feat(api/src/model/customer y address)modelos autenticacion

---

client/src/Components/Cards/Cards.jsx
client/src/Components/Filter/Filter.jsx
client/src/Redux/Actions/actionsTypes.js
client/src/Redux/Actions/index.js
client/src/Redux/Reducer/index.js

creacion de filtro por precios

fix(client/filter)filtro ordenado precio

---

client/package.json
client/src/.text
client/src/Components/.text
client/src/Components/Authenticate/LoginButton.jsx
client/src/Components/Authenticate/LogoutButton.jsx
client/src/Components/Authenticate/Profile.jsx
client/src/Components/NavBar/NavBar.jsx
client/src/index.js

Authenticate Funcionando - Falta acomodar css y componentes pero FUNCIONA!

Ft(Implementacion de Auth0)-LeanSalvaRolan

---

client/src/Components/Help/Help.jsx
client/src/Components/NavBar/NavBar.jsx

Pruebas Style MUI - salva,lean

---

client/src/Components/Card/Card.jsx
client/src/Components/Footer/Footer.jsx

Hice un refactor a footer aplicando todo contenido de MUI y resolvi un error que tenia en Card, en la consola no salta ningun warning ahora

Refactor(client/src/components/footer)

---

client/src/Components/Authenticate/LoginButton.jsx
client/src/Components/Authenticate/LogoutButton.jsx
client/src/Components/Authenticate/Profile.jsx
client/src/Components/NavBar/NavBar.jsx
client/src/Components/NavBar/NavBar.module.css

refactor a MUI
navbar
auth
avatar y buttons log in log out

refactor-navbar&&auth-salvaarmanasco

---

client/src/Components/Footer/Footer.jsx

ta-iconsFooter-salvaarmanasco

---

api/src/routes/payment.js
client/src/Components/CheckOutSuccess/CheckOutSuccess.jsx
client/src/Redux/Actions/actionsTypes.js
client/src/Redux/Actions/index.js
client/src/Redux/Reducer/index.js

api/src/routes/payment complemento y borrado comentarios
client/src/components/checkoutsuccess modificado estético
client/src/redux acción para obtener orden

(feat client/src/comp/checkoutsuccess)

---

api/src/models/Product.js
client/src/App.js
client/src/Components/Card/Card.jsx
client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/Cart/Cart.jsx
client/src/Components/Cart/Cart.module.css
client/src/Components/Cart/CartContext.jsx
client/src/Components/Cart/CartItem.jsx
client/src/Components/Cart/CartItem.module.css
client/src/Components/Home/Home.jsx
client/src/Components/NavBar/NavBar.jsx

Se creo el carrito y se lo vinculo con la pasarela de pagos, quedo todo funcional

feat(src/component/Cart): realizacion carrito

---

api/src/routes/payment.js
client/src/Components/Cards/Cards.jsx

ref-searchbarToMui-salvaarmanasco

---

api/src/routes/payment.js
client/src/Components/Card/Card.jsx
client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/CardDetail/CardDetail.module.css
client/src/Redux/Actions/index.js

Refactorizado el componente Card 
- Ahora no se puede agregar mas al carrito desde home sino el boton con el icono del carrito te manda directamente a cardDetail donde seleccionas el talle y el color y ahi recien lo mandas al carro
- Ahora se puede ver el carrito en Card Details 
- Sacado el error con el modelo payment del back
- Ahora en las actions de Redux se va a tener que usar el .env, en sus archivos .env agregar la variable "REACT_APP_URL = http://localhost:3001/"

refactor/fix(actions redux & payment api)

---

client/src/Components/Cards/Cards.jsx
client/src/Components/CheckOutSuccess/CheckOutSuccess.jsx
client/src/Components/Paged/Paged.jsx
client/src/Components/Paged/Paged.module.css
client/src/Components/PagedSearch/PagedSearch.jsx
client/src/Components/PagedSearch/PagedSearch.module.css
client/src/Components/Payment/PayButton.jsx

fix button payment
agregue disabled

fix-buttonPayment-salvaarmanasco

---

api/src/db.js

Agregado el deploy para subir el back

feat(DEPLOY)

---

api/package.json
api/src/routes/Utils/CludinarySettings.js
api/src/routes/cloudinary.js
api/src/routes/index.js
client/package.json
client/src/Components/Form/Form.jsx
client/src/Components/Form/Form.module.css
client/src/Components/Form/Validate.js

Hay que chequear funcionamiento con el resto de los cambios que se hicieron..

Refactor(client-Form)Implementacion de Cloudinary

---

client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/Cart/Cart.jsx
client/src/Components/Cart/CartItem.jsx
client/src/Components/Payment/PayButton.jsx

Funcionalidad y Estilo para el Boton de CheckOut

fix(src/component/Cart):  botones

---

client/src/Components/NavBar/NavBar.jsx

fix-navbar-buttonCart-salvaarmanasco

---

client/src/Components/Cards/Cards.jsx

ref-cards-MUI-salvaarmanasco

---

client/src/Components/Authenticate/LoginButton.jsx
client/src/Components/Card/Card.jsx
client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/Cards/Cards.jsx
client/src/Components/CheckOutSuccess/CheckOutSuccess.jsx
client/src/Components/Error/Error.jsx
client/src/Components/Filter/Filter.jsx
client/src/Components/Footer/Footer.jsx
client/src/Components/Form/Form.jsx
client/src/Components/Form/Validate.js
client/src/Components/Help/Help.jsx
client/src/Components/Home/Home.jsx
client/src/Components/LandingPage/LandingPage.jsx
client/src/Components/Paged/Paged.jsx
client/src/Components/PagedSearch/PagedSearch.jsx
client/src/Components/Payment/PayButton.jsx
client/src/Redux/Actions/index.js
client/src/Redux/Reducer/index.js
client/src/index.js

Refactorize casi todos los componentes, borre codigo que estaba de mas y cosas que no se usan, pase todo a arrow function y deje todo funcionando

refactor(client/src)

---

client/src/Components/About/About.jsx

responsive-about-salvaarmanasco

---

client/src/Components/Authenticate/LoginButton.jsx
client/src/Components/Authenticate/LogoutButton.jsx
client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/Cards/Cards.jsx
client/src/Components/Cart/Cart.jsx
client/src/Components/CheckOutSuccess/CheckOutSuccess.jsx
client/src/Components/Error/Error.jsx
client/src/Components/Footer/Footer.jsx
client/src/Components/Help/Help.jsx
client/src/Components/NavBar/NavBar.jsx
client/src/Components/Payment/PayButton.jsx

se paso a espanhol los componentes correspondientes

fix(src/component): correccion de idioma

---

client/src/Components/Help/Help.jsx
client/src/Components/NavBar/NavBar.jsx

Fix navbar tamanio salvaarmanasco

---

client/src/Components/Form/Form.jsx

responsive-form-salvaarmanasco

---

api/src/db.js
client/src/Components/Form/Form.jsx
client/src/Redux/Actions/index.js

Acomode las rutas para que todos tengamos lo mismo y sea mas facil realizar los cambios al mergear a MAIN.
DATOS EN DRIVE!
API-SRC-DB:
CLIENT-SRC-REDUX-ACTIONS-INDEX:

Cambios para unificar rutas - lean

---

client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/CardDetail/CardDetail.module.css

refactor(client/src/components/cardDetail)

---

api/src/db.js
api/src/models/Image.js
api/src/models/Product.js
api/src/routes/Controllers/productsController.js
api/src/routes/products.js

Se agrega modelo de imagenes y su tabla con relacion a color SIN TOCAR el resto de funcionamiento general.

Modelo de imagenes

---

client/src/Components/Cards/Cards.jsx

fix-responsive-home-salvaarmanasco

---

api/src/routes/Controllers/productsController.js
client/src/Components/CardDetail/CardDetail.jsx

fix(modeloImag)aceptar

---

client/src/Components/CheckOutSuccess/CheckOutSuccess.jsx

Corrección-Sino se rompe

---

client/src/Components/Cards/Cards.jsx

fix cuando no se muestran productos

Fixes responsive home salvaarmanasco

---

client/src/Components/Cards/Cards.jsx
client/src/Components/Paged/Paged.jsx
client/src/Components/Paged/Paged.module.css
client/src/Components/PagedSearch/PagedSearch.jsx

fix del paginado con responsive grid material ui

fix-pagination&&responsive-salvaarmanasco

---

client/src/Components/Filter/Filter.jsx

se soluciono el warning que tiraba los filtros

Fix(src/component/filter) : fix warning

---

client/src/Components/LandingPage/LandingPage.jsx

Elimine el roll de la landing page porque me parecio incesesario y tiraba un warning

fix(client/components/landingpage)

---

api/src/models/PurchaseOrder.js
api/src/models/ShoppingCart.js
api/src/models/ShoppingList.js
api/src/routes/Controllers/customerController.js
api/src/routes/Controllers/ordersController.js
api/src/routes/orders.js
api/src/routes/payment.js

controllers y rutas de ordenes y modificaciones para los usuarios  (para el panel de admin)

(feat api/src/routes) ordenes back

---

api/src/models/PurchaseOrder.js
api/src/models/ShoppingCart.js
api/src/models/ShoppingList.js
api/src/routes/Controllers/customerController.js
api/src/routes/Controllers/ordersController.js
api/src/routes/orders.js
api/src/routes/payment.js
client/src/App.js
client/src/Components/Authenticate/Profile2.jsx
client/src/Components/Authenticate/adminbutton.jsx
client/src/Components/Cart/Cart.jsx
client/src/Components/CheckOutSuccess/CheckOutSuccess.jsx
client/src/Components/CheckOutSuccess/emailsuccess.js
client/src/Components/Orders/Orders.jsx
client/src/Components/Orders/emailorder.js
client/src/Components/Orders/emailuser.js
client/src/Components/Orders/listorders.jsx
client/src/Components/Orders/listusers.jsx
client/src/Components/Payment/PayButton.jsx
client/src/Redux/Actions/actionsTypes.js
client/src/Redux/Actions/index.js

se hizo
- lista de ordenes (con detalles al producto y demás)
- lista de usuarios (con modificación y borrado)
- ordenes por perfil (en cada perfil ya se actualiza con las ordenes)
- notificaciones por email (para compra exitosa, borrado de cuenta y estado de la orden)
- filtros y modificación de estados de ordenes

Piedra varios front

---

client/src/Components/LandingPage/LandingPage.jsx

Se hace responsive la Landing Page.

Landing responsive

---

api/src/routes/index.js

fix api/src/routes ruta de ordenes

---

client/src/Components/Cart/Cart.jsx

Fix:(src/component/cart.jsx)

---

client/src/Components/Cart/CartDetail.jsx

Logica del Boton de Inicio de Boton - Pago - Registro

Fix(src/component/cart/cartDetail)

---

client/src/Components/Form/Form.jsx

Corrección para que funcionen los filtros correctamente.

Fix form lean

---

client/src/Components/Card/Card.jsx
client/src/Components/NavBar/NavBar.jsx

Solucionado estilos de Cards en Home page
Solucionado el padding right del menu de cuentas

fix(STYLES)

---

client/src/Components/Cart/Cart.jsx
client/src/Components/Cart/CartContext.jsx

Se paso los alert a la libreria de SweetAlert2

feat(src/component/cart): alertas

---

api/src/routes/Controllers/customerController.js
api/src/routes/Controllers/ordersController.js
api/src/routes/Controllers/productsController.js
api/src/routes/products.js
client/package.json
client/src/Components/Acount/Orders.jsx
client/src/Components/Authenticate/Profile2.jsx
client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/Cards/Cards.jsx
client/src/Components/Cart/CartContext.jsx
client/src/Components/CheckOutSuccess/CheckOutSuccess.jsx
client/src/Components/CheckOutSuccess/table.jsx
client/src/Components/Orders/Orders.jsx
client/src/Components/Orders/listorders.jsx
client/src/Components/Orders/listusers.jsx
client/src/Components/Paged/Paged.jsx

fix de errores y panel de admin

fix api/src/routes client/src/comp

---

client/src/Components/Cards/Cards.jsx
client/src/Components/Filter/Filter.jsx

se puede buscar por nombre o anime cuando se tiene otro filtro activo

searchBar por nombre/anime.

---

client/src/Components/LandingPage/LandingPage.jsx
client/src/Components/TopDate/TopDate.jsx
client/src/Components/TopDate/TopDate.module.css
client/src/Redux/Actions/actionsTypes.js
client/src/Redux/Actions/index.js
client/src/Redux/Reducer/index.js

Se crea componente TopDate.
Landing, se renderiza topDate con logica correcta de Mayor a Menor.
Top 5 de nuevos productos.

Feat(components/TopDate/Landing)

---

api/src/routes/payment.js
client/src/Components/CheckOutSuccess/CheckOutSuccess.jsx

- modificación de precio de productos y id de orden

fix api/src/routes/payment y client/src/comp

---

api/src/db.js
api/src/models/RankProduct.js
api/src/routes/Controllers/rankcontroller.js
api/src/routes/index.js
api/src/routes/rankproduct.js
client/src/Components/SignIn/SingIn.jsx
client/src/Components/SignIn/Validate.js

Backend de Ranking de productos por Reviws de usuario
Modelo / Controller y Routes
Fix de Validacion de direcciones en SignIn

Rank model

---

client/src/App.js
client/src/Components/About/About.jsx
client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/Cards/Cards.jsx
client/src/Components/Help/Help.jsx
client/src/Components/LandingPage/LandingPage.jsx
client/src/Components/Shop/Shop.jsx
client/src/index.js

Solucione el error del footer que siempre se veia raro, ahora siempre esta abajo (Avisar si se me paso en algun componente), tambien el componente CART ser renderiza en toda la pagina, para que se vea desde cualquier lado, no solo desde algunos componentes especificos (Avisar si hay algun bug o algo relacionado a que se vea en todos lados)

refactor(client/components)

---

client/src/Components/Cards/Cards.jsx
client/src/Components/LandingPage/LandingPage.jsx
client/src/Components/TopDate/TopDate.jsx
client/src/Components/TopRanked/TopRanked.jsx

Agregado iconos de carga en los renderizados

refactor(client/component)

---

client/src/Components/Card/Card.jsx
client/src/Components/CardRanked/CardRanked.jsx
client/src/Redux/Reducer/index.js

Se hizo el borrado logico en el front y se le aplico estilo a las card

feat: (src/card) - (src/action/index)

---

client/src/Components/Card/Card.jsx
client/src/Components/CardDetail/CardDetail.jsx

se crearon los botones favoritos con sus alertas, falta agregar la funcion correspondiente

fear:(src/card - cardDetail)

---

client/src/Components/SignIn/SingIn.jsx

Cambia las comunas por ciudades importantes nomas

fix(Provinciasycomunas)

---

api/src/routes/Controllers/customerController.js
api/src/routes/Controllers/ordersController.js
api/src/routes/Controllers/productsController.js
api/src/routes/customer.js
api/src/routes/orders.js
client/src/Components/Orders/Orders.jsx
client/src/Components/Orders/Validate.js
client/src/Components/Orders/listUsers2.jsx
client/src/Components/Orders/listorders.jsx
client/src/Components/Orders/listproducts.jsx
client/src/Components/Orders/listusers.jsx
client/src/Components/SignIn/registerEmail.js
client/src/Redux/Actions/actionsTypes.js
client/src/Redux/Actions/index.js

se hizo: 
- modificación lista de usuarios, ordenes
- creación lista de productos con validado y borrado
- -modificación rutas del back para las ordenes

feat client/src/comp fix api/src/routes

---

api/src/models/Customer.js
api/src/routes/customer.js

Arreglado la ruta y el controller de customer

fix(api/src/customer)

---

api/src/routes/Controllers/customerController.js
api/src/routes/customer.js

Agregado todas las rutas de wishlist y funcionando
- PUT customer/wishList
> - [ ] req.body (id, wishList (NUMERO))
- DELETE customer/wishList
> - [ ] req.body (id, productId(NUMERO))

feat(api/src/routes)

---

client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/Cards/Cards.jsx
client/src/Components/LandingPage/LandingPage.jsx

fix-cardDetail

---

api/src/routes/Controllers/productsController.js
client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/CardDetail/RatingList.jsx

fix-errors-products

---

client/src/Components/CardDetail/CardDetail.jsx

fix-carddetailSalva1

---

api/src/routes/Controllers/productsController.js
client/src/Components/Acount/Acount.jsx
client/src/Components/Acount/WishList.jsx
client/src/Components/Card/Card.jsx
client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/Cards/Cards.jsx
client/src/Redux/Actions/actionsTypes.js
client/src/Redux/Actions/index.js
client/src/Redux/Reducer/index.js

- Se agregaron comprobaciones y un texto para que el usuario si no esta registrado no puede acceder al panel de usuarios
- Se termino la logica de wishlist, esta funcionando con todas las pruebas correspondientes, ahora hay un estado y una accion en el reducer que controla la wishlist del usuario
- Ahora la pagina no rompe cuando el usuario no esta registrado pero accede a los productos
- Tambien cuando se recargan las paginas (se limpia el cache y se limpia el estado que tiene el usuario) no se rompe
- Se quitaron algunos console.log que eran molestos en el back

Ta wishlist santirbe98

---

client/src/Components/Help/Help.jsx

Help component

---

client/src/Components/CardDetail/CardDetail.jsx

fix resonsive card detail
rompian algunos productos dependiendo el tama;o del nombre

fix-responsive-carddetail

---

client/src/Components/Cart/CartDetail.jsx

se soluciono un bug en el componente de cartDetail

fix(src/component/cartDetail)

---

api/src/routes/Controllers/ordersController.js

le saque un console.log que era muy largo y parecia que rompia

fix(api/src)

---

api/src/routes/Controllers/customerController.js
client/src/Components/CardDetail/CardDetail.jsx

Corregido el cambio automatico entre colores.
Se saca console.log de customer

Fix carrousel card detail

---

api/src/models/RankProduct.js
client/src/Components/CardRanked/CardRanked.jsx
client/src/Components/Cards/Cards.jsx
client/src/Components/Cart/Cart.jsx
client/src/Components/Cart/CartDetail.jsx
client/src/Components/TopDate/TopDate.jsx
client/src/Components/TopRanked/TopRanked.jsx

visualización de nombres (mas cortos) y estrellas (mas exacto el promedio) en  landing y pagina de compra

otacuNames y estrellas

---

client/src/Components/Acount/Acount.jsx
client/src/Components/SignIn/SingIn.jsx

se pasaron a sweetAlert los alertas de Acount y SingIn

feat:(src/component/ acount - singin)

---

api/src/routes/Controllers/productsController.js
client/src/Components/Acount/Orders.jsx
client/src/Components/CardDetail/CardDetail.jsx
client/src/Components/CardDetail/RatingList.jsx

- correción de precios de delivery y costo en el apartado amount
- botón de borrado de comentarios en los productos con reseña si eres administrador

feat client/src/rating fix clien/src/acount

---

client/src/Components/Acount/Acount.jsx
client/src/Components/Cart/CartDetail.jsx

resonsive account && cartdetail juanete y salva

responsive-account&&catdetail-salvayjuanete

---

client/src/Components/Acount/Acount.jsx
client/src/Components/Acount/Orders.jsx
client/src/Components/Acount/Rated.jsx

Fix de Reviews de producto y Lista de productos calificados

fix(client/src/Components/Acount)

---

client/src/Components/Acount/Acount.jsx
client/src/Components/Acount/Orders.jsx

Agregado cargas al usuario y solucionado un error que habia que no permitia puntuar los productos

Ta responsive2 santirbe98

---

api/src/db.js
api/src/models/Product.js
api/src/routes/Controllers/categoriesController.js
api/src/routes/Controllers/customerController.js
api/src/routes/index.js
api/src/routes/products.js

Limpieza de codigo comentado que no se usa mas y consoles.log inecsesarios

refactor(api)

---

client/src/Components/Cart/CartContext.jsx
client/src/Components/Cart/CartDetail.jsx

Se soluciono el alert que salia luego de realizar la compra y se creo un handleClean en el boton que hace referencia al limpiado del carrito

fix(src/component/cart)

---

client/src/Components/Cards/Cards.jsx
client/src/Components/Filter/Filter.jsx
client/src/Components/LandingPage/LandingPage.jsx
client/src/Components/TopDate/TopDate.jsx
client/src/Components/TopRanked/TopRanked.jsx
client/src/Redux/Reducer/index.js

Mensaje de "no encontrados" centrado
agrega dos botones para orden por votos y nuevos.
landing correccion de cards a mostrar.

mejora landingy ordenamiento

---

client/src/Components/Acount/Acount.jsx
client/src/Components/Acount/Orders.jsx
client/src/Components/Acount/Rated.jsx
client/src/Components/Acount/WishList.jsx
client/src/Components/Cart/CartContext.jsx
client/src/Components/SignIn/SingIn.jsx

se hizo responsive los alert restantes y se soluciono el responsive del form para modificar el usuario

fix(src/component)

---

api/src/routes/Controllers/productsController.js
api/src/routes/Controllers/rankcontroller.js
api/src/routes/rankproduct.js
client/src/Components/Acount/Acount.jsx
client/src/Components/Acount/Orders.jsx
client/src/Components/CardDetail/RatingList.jsx
client/src/Components/CheckOutSuccess/CheckOutSuccess.jsx
client/src/Components/Form/Form.jsx

No nos maten . Eran cosas que había que arreglar! 
Probamos todo.. 
Prueben nuevamente!

Fix- Eliminar comentarios y varios errores
